Alert_Services/Alert_Services/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	#routes to admin site
    url(r'^admin/', include(admin.site.urls)),
    #routes to reddit_notifier site
    url(r'^', include('reddit_notifier.urls', namespace="reddit_notifier")),
]

Alert_Services/reddit_notifier/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.index, name='index'),
    # ex: /signup
    url(r'^signup/$', views.signup, name='signup'),
    # ex: /my_account
    url(r'^my_account/$', views.my_account, name='my_account'),
    # POST to create subscription
    url(r'^create_subscription/$', views.create_subscription, name='create_subscription'),
    # POST to delete subscription
    url(r'^delete_subscription/$', views.delete_subscription, name='delete_subscription'),
    # POST for getting a subreddit post sent via SMS
    url(r'^get_subreddit_post/$', views.get_subreddit_post, name='get_subreddit_post'),
    # POST for authentication
    url(r'^authenticate/$', views.authentication, name='authentication'),
    # POST for logout
    url(r'^logout/$', views.request_logout, name='request_logout'),
]

Alert_Services/reddit_notifier/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

"""Subscription model used to store User subscription."""
class Subscription(models.Model):
	user = models.ForeignKey(User)
	subreddit = models.CharField(max_length = 200)
	frequency = models.IntegerField(default = 60)

"""Model used to store the results of a request for a given subreddit."""
class CachedItem(models.Model):
	subreddit = models.CharField(max_length = 200)
	text = models.CharField(max_length = 200)
	url = models.CharField(max_length = 200)
	last_updated = models.DateTimeField('last updated')

Alert_Services/reddit_notifier/views.py
from .models import Subscription
from django.contrib.auth.models import User
from tasks import *
from notification_functions import *
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import json

"""Returns the homepage."""
def index(request):
	if request.user.is_authenticated():
		context = {'loggedin':True}
	else:
		context = {'loggedin':False}
	return render(request, 'reddit_notifier/index.html', context)

"""Parses POST request and creates new User. Logs user in if successful. Redirects to homepage."""
def signup(request):
	username = request.POST.get('phone_number', False)
	password = request.POST.get('user_password', False)
	first_name = request.POST.get('first_name', False)
	last_name = request.POST.get('last_name', False)
	new_user = User.objects.create_user(username = username, password = password, first_name = first_name, last_name = last_name)
	new_user.save()
	user = authenticate(username=username, password=password)
	if user is not None:
		login(request, user)
	return HttpResponseRedirect(reverse('reddit_notifier:index'))

"""Responds to user request to have most recent post from a given subreddit
	texted to their phone. Returns a json containing a message concerning the response result."""
def get_subreddit_post(request):
	phone_num = request.POST.get('phone_number', False)
	subreddit = request.POST.get('subreddit_name', False)
	response = fetch_subreddit(subreddit)
	server_response = {}
	if response:
		success = send_message(response, phone_num)
		if success:
			server_response['result'] = 'Message sent successfully!'
		else:
			server_response['result'] = 'An error occurred while contacting Twilio. :('
	else:
		server_response['result'] = 'An error occurred while contacting Reddit. Please check the name of your subreddit. :('
	return HttpResponse(json.dumps(server_response), content_type = "application/json")

"""Delivers the my_account page if the user is logged in."""
@login_required()
def my_account(request):
	subscriptions_list = Subscription.objects.filter(user=request.user)
	context = {'subscriptions_list':subscriptions_list, 'user_name':request.user.first_name}
	return render(request, 'reddit_notifier/my_account.html', context)

"""Creates a Subscription object for given user per request."""
@login_required()
def create_subscription(request):
	subreddit_name = request.POST.get('subreddit_name', False)
	frequency = request.POST.get('frequency', False)
	if not frequency == False:
		frequency = int(frequency)
	new_subscription = Subscription(user = request.user, subreddit = subreddit_name, frequency = frequency)
	new_subscription.save()
	fetch_subreddit(subreddit_name) #this just ensures that the subreddit winds up in CachedItems if it isn't already so that it is present when attempting to fulfill subscription
	return HttpResponseRedirect(reverse('reddit_notifier:my_account'))

"""Removes a Subscription object for a given user per request."""
@login_required()
def delete_subscription(request):
	subscription_id = request.POST.get('subscription_id')
	subscription = Subscription.objects.filter(id = subscription_id)
	if subscription:
		subscription.delete()
	return HttpResponseRedirect(reverse('reddit_notifier:my_account'))

"""Verifies user authentication for sign in."""
def authentication(request):
	phone_num = request.POST.get('phone_number', False)
	password = request.POST.get('user_password', False)
	user = authenticate(username=phone_num, password=password)
	if user is not None:
		login(request, user)
	return HttpResponseRedirect(reverse('reddit_notifier:index'))

"""Logs a user out."""
def request_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('reddit_notifier:index'))

Alert_Services/reddit_notifier/templates/reddit_notifier/index.html
{% load static from staticfiles %}
<html>
<head>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'reddit_notifier/css/styles.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="{% static 'reddit_notifier/js/scripts.js' %}"></script>
	<link href='https://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>	
	<title>PromptWorks Reddit Machine!</title>
</head>
<body>
	<div id="title_bar">
		{% if loggedin %}
			<div id="logout_button_box" class="pull-right">
				<form action="{% url 'reddit_notifier:request_logout' %}" method="post"> 
					{% csrf_token %}
					<button type="submit" class="btn btn-primary pull-right title_bar_button">Log out</button>
					<a class="nav-link"href="{% url 'reddit_notifier:my_account' %}"><button type="button" id="launch_signup_button" class="btn btn-primary pull-right title_bar_button">My Account</button></a>
				</form>
			</div>
		{% else %}
			<button type="button" id="launch_signup_button" class="btn btn-primary pull-right title_bar_button" data-toggle="modal" data-target="#signUpModal" >Sign up</button>
			<button type="button" id="launch_signin_button" class="btn btn-primary pull-right title_bar_button" data-toggle="modal" data-target="#signInModal" >Sign in</button>
		{% endif %}
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<h1 class="text-center header_text">Use the form below to have the latest subreddit post sent to your phone!</h1>
			</div>
			<div class="col-md-2"></div>
		</div>
		<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6" id="request_text_form">
					<form action="{% url 'reddit_notifier:get_subreddit_post' %}" method="post"> 
			        	{% csrf_token %}
			        	<label for="phone_number" class="control-label">Phone Number</label>
			            <input type="text" class="form-control" name="phone_number" id="phone_number">
			            <label for="subreddit_name" class="control-label">Subreddit Name</label>
			            <input type="text" class="form-control" name="subreddit_name" id="subreddit_name">
			        	<input type="submit" class="btn btn-default" value="Send Message" /> 
			    	</form>
				</div>
				<div class="col-md-3"></div>
		</div>
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6" id="alert_message_box"></div>
			<div class="col-md-3"></div>
		</div>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<h1 id="info_text" class="text-center">Use the links above if you'd like to create an account for recurring updates!</h1>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>

	<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="signInModal">
	  <div class="modal-dialog modal-sm" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="signInModalLabel">Sign In</h4>
	      </div>
	      <div class="modal-body">
	        <form action="{% url 'reddit_notifier:authentication' %}" method="post"> 
	        	{% csrf_token %}
	        	<label for="phone_number" class="control-label">Phone Number</label>
	            <input type="text" class="form-control" name="phone_number" id="phone_number">
	            <label for="user_password" class="control-label">Password</label>
	            <input type="text" class="form-control" name="user_password" id="user_password">
	        	<input type="submit" class="btn btn-default" value="Log In" /> 
	    	</form>
	      </div>
	  	</div>
	  </div>
	</div>

	<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModal">
	  <div class="modal-dialog modal-sm" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="signUpModalLabel">Sign Up</h4>
	      </div>
	      <div class="modal-body">
	        <form action="{% url 'reddit_notifier:signup' %}" method="post"> 
	        	{% csrf_token %}
	        	<label for="first_name" class="control-label">First Name</label>
	            <input type="text" class="form-control" name="first_name" id="first_name">
	            <label for="last_name" class="control-label">Last Name</label>
	            <input type="text" class="form-control" name="last_name" id="last_name">
	        	<label for="phone_number" class="control-label">Phone Number</label>
	            <input type="text" class="form-control" name="phone_number" id="phone_number">
	            <label for="user_password" class="control-label">Password</label>
	            <input type="text" class="form-control" name="user_password" id="user_password">
	        	<input type="submit" class="btn btn-default" value="Sign Up" /> 
	    	</form>
	      </div>
	  	</div>
	  </div>
	</div>

	<script type="text/javascript">
		$('#request_text_form').on('submit', function(event){
			$('#alert_message_box').html("<div></div>"); //clear any previous messages.
			event.preventDefault();
			send_message_request();
		});
	</script>
</body>
</html>

Alert_Services/reddit_notifier/templates/reddit_notifier/my_account.html
{% load static from staticfiles %}
<html>
<head>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'reddit_notifier/css/styles.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<link href='https://fonts.googleapis.com/css?family=Dosis:400,700' rel='stylesheet' type='text/css'>	
	<title>{{user_name}}'s Account!</title>
</head>
<body>
	<div id="title_bar">
		<div id="logout_button_box" class="pull-right">
			<form action="{% url 'reddit_notifier:request_logout' %}" method="post"> 
				{% csrf_token %}
				<button type="submit" class="btn btn-primary pull-right title_bar_button">Log out</button>
				<a class="nav-link"href="{% url 'reddit_notifier:index' %}"><button type="button" id="launch_signup_button" class="btn btn-primary pull-right title_bar_button">Homepage</button></a>
			</form>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6" id="create_sub_box">
				<h1 class="text-center">Create a new subscription here:</h1>
				<form action="{% url 'reddit_notifier:create_subscription' %}" method="post"> 
		        	{% csrf_token %}
		            <label for="subreddit_name" class="control-label">Subreddit Name</label>
		            <input type="text" class="form-control" name="subreddit_name" id="subreddit_name">
		            <input type="radio" name="frequency" value="2" checked> Every 2 Minutes   
		            <input type="radio" name="frequency" value="60" > Every Hour    
		            <input type="radio" name="frequency" value="1440" > Once Per Day    
		            <br>
		        	<input type="submit" class="btn btn-default" value="Create" /> 
		    	</form>
			</div>
			<div class="col-md-3"></div>
		</div>
		<div class="row">
			<div class="col-md-12" id="subscriptions_box">
				{% if subscriptions_list %}
				<h1 class="text-center">Your Current Subscriptions.</h1>
				{% else %}
				<h1 class="text-center">No Current Subscriptions.</h1>
				{% endif %}
				<ul>
					{% for subscription in subscriptions_list %}
					<li>
						<form action="{% url 'reddit_notifier:delete_subscription' %}" method="post"> 
				        	{% csrf_token %}
				        	<label for="first_name" class="control-label">Subreddit:  {{subscription.subreddit}},</label>
				        	{% if subscription.frequency == 2 %}
				        		<label for="first_name" class="control-label">(Every 2 Minutes)</label>
				        	{% elif subscription.frequency == 60 %}
				        		<label for="first_name" class="control-label">(Every Hour)</label>
				        	{% else %}
				        		<label for="first_name" class="control-label">(Once Per Day)</label>
				        	{% endif %}

				        	<input type="hidden" name="subscription_id" value="{{subscription.id}}">
				        	<input type="submit" class="btn btn-default" value="Delete" /> 
				    	</form>
		    		</li>
		    		{% endfor %}
		    	</ul>
			</div>
		</div>
	</div>
</body>
</html>